### ISSUE TITLE
Documentation on how to set region, key and secret

### ISSUE THREAD

**Issue by tacman** [cloudyr/aws.sqs#3]
This is probably a dumb question, but we're stuck trying to connect to an existing queue, but can't figure out how to initialize it with the  region, key and secret.  

If the README file included a sample with those parameters we'd probably be able to start reading fro the queue.  Any suggestions?

**Comment by leeper** [comment]
Sorry about that! This was poorly documented. You can pass region, key, and secret to every function (via the `...` argument). Or, more easily, you can set these values as environment variables (inside or outside of R). I've updated the docs accordingly.
