### ISSUE TITLE
Problems deleting a message

### ISSUE THREAD

**Issue by jdgodchaux** [cloudyr/aws.sqs#4]
Hello @leeper! Thank you for the excellent client package! I'm having some trouble deleting a message from my SQS queue and I'm not sure if it's something I'm doing wrong or some issue with the package. 

I have a queue called "input" on AWS SQS with full permissions allowing all SQS actions, and I'm able to pull a singe message down from the queue with the following:

```
input <- receive_msg("input")
```

I'm able to see data in the variable input and can print the ReceiptHandle to the console:

```
> input$ReceiptHandle[1]
[1] "Long_String_of_Random_Letters_and_Numbers...."
```

However, when I attempt to delete the message in the queue, here's what I'm seeing:

```
> delete_msg("input", input$ReceiptHandle[1])
No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
Error in structure(content(r, "text"), "unknown") : 
  attributes must be named
```

Any chance my problem is tied to the UTF-8 encoding the console is complaining about? Is there anything about this error that jumps out to you?

Thank you!!

**Comment by leeper** [comment]
This looks like it is the result of a typo, which I've now fixed. Can you reinstall from GitHub and let me know if you're still encountering the issue? I imagine you might be because the typo was in an error-reporting line; I'm hoping with the fix the error message will at least be more informative.

One thing to try is running your code in a `with_verbose()` statement which can sometimes be more useful:

``` R
httr::with_verbose(delete_msg("input", input$ReceiptHandle[1]))
```

Let me know what you find after an update.

**Comment by leeper** [comment]
@jdgodchaux Just wanted to see if this was working correctly for you now or if you were still encountering problems?

**Comment by honggao110** [comment]
Hello @leeper, thanks for developing this R package! I'm working with @jdgodchaux to set up R and SQS. I was testing deleting message, but I got errors. Here's what I saw: 

<img width="414" alt="screen shot 2016-02-26 at 5 41 48 pm" src="https://cloud.githubusercontent.com/assets/14278012/13403142/928cae80-dee1-11e5-9190-e0b31ac05f81.png">

Is this something I did wrong when I tried to delete the message? Do you have any suggestions? 

Thanks!

**Comment by jdgodchaux** [comment]
@leeper Thanks very much for your response! @honggao110 and I are working together on this, and we're seeing similar problems now. I saw this error message first:

```
> # remove original SQS message from input SQS queue
> aws.sqs::delete_msg("input", input$ReceiptHandle[1])
No encoding supplied: defaulting to UTF-8.
Error in if (!repeated && grepl("%[[:xdigit:]]{2}", URL, useBytes = TRUE)) return(URL) : 
  missing value where TRUE/FALSE needed
```

But in subsequent runs, I'm seeing the same error message @honggao110 is seeing:

```
> # remove original SQS message from input SQS queue
> aws.sqs::delete_msg("input", input$ReceiptHandle[1])
No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
Error in out$DeleteMessageResponse : 
  $ operator is invalid for atomic vectors
```

Any insight would be much appreciated!

**Comment by leeper** [comment]
Thanks, @jdgodchaux and @honggao110! I think I've fixed this. Several issues here, one of which was just a stupid typo (as is so often the case).

**Comment by honggao110** [comment]
Hi @leeper, I just tested it and it works for me. Thanks for fixing this! It works great!

**Comment by leeper** [comment]
@honggao110 Excellent! Let me know if you encounter further issues.
