### ISSUE TITLE
send_msg is not in the exported NAMESPACE

### ISSUE THREAD

**Issue by ludov04** [cloudyr/aws.sqs#6]
Hey,

Some functions documented in the README.md are not exported in the NAMESPACE.

It would be nice to have it so we don't have to use the `:::` notation to use the function.

Thanks

**Comment by leeper** [comment]
I think this is [now fixed](https://github.com/cloudyr/aws.sqs/commit/1c82e257eca150aa5823360f79e3e913810e7bce), @ludov04. Sorry about that.
